markdown: kramdown
test_unit_version: 3.5.2
test_unit_release_date: 2021-12-10
test_unit_rails_version: 6.1.0
test_unit_rails_release_date: 2021-01-13
test_unit_activesupport_version: 1.0.9
test_unit_activesupport_release_date: 2017-06-26
test_unit_full_version: 0.0.5
test_unit_full_release_date: 2016-10-16
test_unit_capybara_version: 1.1.1
test_unit_capybara_release_date: 2021-03-15
test_unit_rr_version: 1.0.5
test_unit_rr_release_date: 2016-01-18

kramdown:
  enable_rouge: true
