markdown: kramdown
test_unit_version: 3.3.3
test_unit_release_date: 2019-05-10
test_unit_rails_version: 5.2.2
test_unit_rails_release_date: 2018-08-20
test_unit_activesupport_version: 1.0.9
test_unit_activesupport_release_date: 2017-06-26
test_unit_full_version: 0.0.5
test_unit_full_release_date: 2016-10-16
test_unit_capybara_version: 1.0.7
test_unit_capybara_release_date: 2018-08-27
test_unit_rr_version: 1.0.5
test_unit_rr_release_date: 2016-01-18

kramdown:
  enable_rouge: true
